@startuml
'https://plantuml.com/sequence-diagram
title Interactions of ""repository.bookingFor(id)""
skinparam handwritten true
skinparam defaultFontName Chalkboard

participant "Domain logic" as Domain
participant ShardedBookings as ShardedBookings
participant Sharding as Sharding
participant BookingCommandProtocol as BookingCommandProtocol1
participant CommandSender as CommandSender
autonumber
autoactivate on

Domain -> ShardedBookings: bookingFor(id)
ShardedBookings -> Sharding: entityFor(id)
Sharding -> BookingCommandProtocol1: clientFor(id)
BookingCommandProtocol1 -> CommandSender: senderForID(id)
return nat = ""OutgoingCommand[*] ~> F""

return client = BookingAlg[F]
note right: Actor messaging is represented by a natural transformation

return BookingAlg[F]
@enduml