@startuml
'https://plantuml.com/sequence-diagram
title Interactions of ""repository.bookingFor(id)""
skinparam handwritten true
skinparam defaultFontName Chalkboard

participant "Domain logic" as Domain
participant BookingRepository as BookingRepository
participant Repository as Repository
participant BookingCommandProtocol as BookingCommandProtocol1
participant CommandSender as CommandSender
autonumber
autoactivate on

Domain -> BookingRepository: bookingFor(id)
BookingRepository -> Repository: entityFor(id)
Repository -> BookingCommandProtocol1: clientFor(id)
return client = BookingAlg[OutgoingCommand[*]]
BookingCommandProtocol1 -> CommandSender: senderForID(id)
return nat = ""OutgoingCommand[*] ~> F""
return BookingAlg[F]
note right: Actor messaging is represented by a natural transformation↑

return BookingAlg[F]
@enduml